- hosts: toolshedservers
  become: true
  become_user: root
  vars:
     # systemd
    galaxy_manage_systemd: yes


  pre_tasks:
    - name: Install Dependencies
      apt:
         name: ['acl', 'bzip2', 'git', 'make', 'python3-pip', 'python3-virtualenv', 'tar', 'virtualenv', 'mercurial', 'supervisor', 'libglib2.0-dev', 'zutils', 'unzip', 'rsync']
    - name: Add toolshed user
      ansible.builtin.user:
        name: toolshed

  roles:
    - role: galaxyproject.galaxy
      become_user: "toolshed"
      galaxy_manage_clone: yes
      galaxy_manage_static_setup: yes
      galaxy_manage_mutable_setup: yes
      galaxy_manage_database: no
      galaxy_manage_paths: yes
      galaxy_build_client: false
      galaxy_fetch_eggs: yes
      galaxy_manage_systemd: false

    - role: galaxyproject.galaxy_toolshed
      become_user: "toolshed"
      galaxy_toolshed_manage_static_setup: yes
      galaxy_toolshed_manage_database: yes
      galaxy_manage_systemd: true
      galaxy_build_client: true
    - galaxyproject.nginx

  post_tasks:
    - name: Fix unwanted privsep permissions on server
      file:
        path: "{{ galaxy_server_dir }}"
        owner: toolshed
        group: toolshed
        recurse: yes
    - name: Ansible copy file to remote server
      copy:
          src: "{{ galaxy_server_dir }}/static/"
          dest: "/var/www/tsstatic/"
          group: www-data
          owner: www-data
          remote_src: true
    - name: Create Tool Shed hgweb dir
      file:
        state: directory
        path: "{{ galaxy_toolshed_mutable_config_dir }}/hgweb_config_dir"
        group: toolshed
        owner: toolshed
    - name: Create Tool Shed hgweb file
      copy:
        content: "[paths]"
        dest: "{{ galaxy_toolshed_mutable_config_dir }}/hgweb_config_dir/hgweb.config"
        force: no
        group: toolshed
        owner: toolshed
    - name: Fixup system service
      block:
        - name: Deploy Toolshed Unit

          template:
            owner: root
            group: root
            mode: 0644
            src: systemd/toolshed.service.j2
            dest: /etc/systemd/system/toolshed.service
          notify:
            - daemon reload

        - name: Enable Toolshed Unit
          systemd:
            name: toolshed.service
            enabled: yes


  handlers:
    - name: Restart Toolshed
      become: yes
      systemd:
        name: toolshed
        state: restarted


  #handlers:
    #- name: Restart Galaxy
      #supervisorctl:
        #name: galaxy
        #state: restarted
