---
- name: Create the ssl-cert group if it doesn't exist
  group:
    name: "{{ certbot_ssl_group }}"
    state: present
    system: yes
  when: certbot_ssl_group is defined

- name: Write the certificate post-renewal hook script
  copy:
    content: |
        #!/bin/bash
        mkdir -p  /etc/ssl/private/
        {% if certbot_ssl_group is defined %}
        chmod {{ certbot_ssl_private_dir_mode | default(750) }} /etc/ssl/private/
        chown root:{{ certbot_ssl_group | default('') }} /etc/ssl/private/
        {% endif %}
        # Chai
        cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/fullchain.pem {{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_trusted_certificate | default('fullchain.pem') }}
        chmod 644  {{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_trusted_certificate | default('fullchain.pem') }}
        chown root:{{ certbot_ssl_group | default('') }}   {{ nginx_ssl_conf_dir }}/{{ nginx_conf_ssl_trusted_certificate | default('fullchain.pem') }}
        # Cert
        cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/cert.pem {{ nginx_conf_ssl_certificate }}
        chmod 644 {{ nginx_conf_ssl_certificate }}
        chown root:{{ certbot_ssl_group | default('') }} {{ nginx_conf_ssl_certificate }}
        # Privkey
        cp {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/privkey.pem {{ nginx_conf_ssl_certificate_key }}
        chmod 640  {{ nginx_conf_ssl_certificate_key }}
        chown root:{{ certbot_ssl_group | default('') }}  {{ nginx_conf_ssl_certificate_key }}
        # For each user, create custom version
        {% if certbot_share_key_users %}
        mkdir -p {{ certbot_share_key_dir }}
        chmod 755 {{ certbot_share_key_dir }}
        chown root:root {{ certbot_share_key_dir }}
        {% endif %}
        {% for user in certbot_share_key_users %}
        cp  {{ certbot_letsencrypt_dir }}/live/{{ certbot_hostname_override | default(certbot_domains[0]) }}/privkey.pem {{ certbot_share_key_dir }}/privkey-{{ user }}.pem
        chown {{ user }}: {{ certbot_share_key_dir }}/privkey-{{ user }}.pem
        {% endfor %}
        # Other
        {{ certbot_post_renewal }}
    dest: "{{ certbot_letsencrypt_dir }}/renewal-hooks/post/ansible.sh"
    owner: root
    group: root
    mode: "0755"
  notify:
    - Execute the certificate post-renewal script
